site_name: Testes de Software
repo_url: https://github.com/arthurrochamoreira/Testes-de-Software
repo_name: testes-de-software

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.sections        
    - navigation.expand
  language: pt-BR
  font:
    text: Roboto Mono
    code: Roboto Mono

  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-5 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

nav:
  - Home: index.md
  - TPI/TPE:
    - TPI/TPE(3): tpi_tpe/tpi3_tpe3.md
    - TPI/TPE(4): tpi_tpe/tpi4_tpe4.md
  - White-Box Testing:
      - Teste Caixa Branca: aae3/white_box_test.md
  - Unit Testing:
      - Teste de Unidade: aae3/unit_test.md
      - Teste de Unidade v2: aae3/unitv2.md
      - Teste de Unidade v3: aae3/unitv3.md
  - MC/DC:
      - Modified Condition/Decision Coverage (MC/DC): aae3/mc_dc.md