site_name: Testes de Software
repo_url: https://github.com/arthurrochamoreira/Testes-de-Software
repo_name: testes-de-software

plugins:
  - search
  - mermaid2

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.sections        
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - announce.dismiss

  language: pt-BR
  font:
    text: Roboto Mono
    code: Roboto Mono
    heading: Montserrat

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-5 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

nav:
  - Home: index.md
  - MC/DC:
      - Modified Condition/Decision Coverage (MC/DC): aae3/mc_dc.md
  - AAE: 
    - AAE3: aae3/aae3.md
  - TPI/TPE:
    - TPI/TPE(3): tpi_tpe/tpi3_tpe3.md
    - TPI/TPE(4): tpi_tpe/tpi4_tpe4.md
  - Unit Testing:
      - Teste de Unidade: aae3/unit_test.md
  - White-Box Testing:
      - Teste Caixa Branca: aae3/white_box_test.md
