site_name: Testes de Software
repo_url: https://github.com/arthurrochamoreira/Testes-de-Software
repo_name: testes-de-software
extra_css:
  - css/custom-general.css
  - css/night-sky.css
  - css/shooting-stars.css
extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - js/interactive.js
  - js/shooting-stars.js
  - js/starfield.js
  - js/night-sky.js
  - js/translate.js

plugins:
  - search
  - mermaid2

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.index
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - announce.dismiss

  language: pt-BR
  font:
    text: Roboto Mono
    code: Roboto Mono
    heading: Montserrat

  palette:
    - scheme: slate
      primary: deep purple
      accent: deep orange

nav:
  - Home: index.md
  - Projetos:
      - Projeto: Projeto/Projeto.md

nav:
  - Home: index.md
  # - MC/DC:
  #    - Modified Condition/Decision Coverage (MC/DC): aae3/mc_dc.md
  # - AAE:
  # - AAE3: aae3/aae3.md
  - TPI/TPE:
      - TPI/TPE(1): tpi_tpe/tpi1_tpe1.md
      - TPI/TPE(2): tpi_tpe/tpi2_tpe2.md
      - TPI/TPE(3): tpi_tpe/tpi3_tpe3.md
      - TPI/TPE(4): tpi_tpe/tpi4_tpe4.md
      - TPI/TPE(5): tpi_tpe/tpi5_tpe5.md
  # - Unit Testing:
  #    - Teste de Unidade: aae3/unit_test.md
  # - White-Box Testing:
  #    - Teste Caixa Branca: aae3/white_box_test.md
